/**
 * Put the two traced halves on ONE coordinate system.
 *
 *   node scripts/normalize-figures.js
 *
 * potrace emits each half at whatever size the autocrop left it (344x698 and
 * 320x712), and each figure sits slightly off its own image centre. Rendered
 * as-is the two views would differ in scale and drift sideways relative to each
 * other, so a zone box fitted on the front would miss on the back.
 *
 * Each figure is therefore scaled to a common body height and translated so its
 * MEASURED midline — not its image centre — lands on the middle of the shared
 * viewBox. Landmarks are re-expressed in that viewBox so lib/bodyMap.js can be
 * fitted to real anatomy.
 *
 * Writes public/figures/figure-{front,back}.svg and lib/figureGeometry.js.
 */
const fs = require('fs');
const path = require('path');

// Matches lib/bodyMap.js VIEW_BOX. 560 tall is inherited from the hand-drawn
// lateral figures; 280 wide is what the traced front view needs at that height
// once its outstretched arms are included (268px) plus a small margin.
const VIEW = { width: 280, height: 560 };
const PAD_Y = 8;                       // keeps the crown and soles off the edge
const BODY_H = VIEW.height - PAD_Y * 2;

const L = JSON.parse(fs.readFileSync('public/figures/landmarks.json', 'utf8'));

/** Centre of a landmark's trunk run, as a fraction of the traced half width. */
const centreOf = (m) => {
  if (!m || !m.runs || !m.runs.length) return null;
  const trunk = m.runs.find(([a, b]) => a <= 0.5 && b >= 0.5) || m.runs[Math.floor(m.runs.length / 2)];
  return (trunk[0] + trunk[1]) / 2;
};

/**
 * The body's own midline. Averaged over neck, waist and armpit rather than
 * taken from one, because a hand-drawn figure is never perfectly symmetric and
 * a single row would tilt the whole alignment.
 */
function midlineOf(view) {
  const parts = ['neck', 'waist', 'armpit'].map((k) => centreOf(view.landmarks[k])).filter((v) => v != null);
  return parts.reduce((a, b) => a + b, 0) / parts.length;
}

function fit(view) {
  const scale = BODY_H / (view.bottom - view.top);
  const mid = midlineOf(view);
  return {
    scale,
    mid,
    // The traced SVG's own origin is the top-left of the cropped bitmap, and
    // the body starts `top` pixels below that.
    tx: VIEW.width / 2 - mid * view.width * scale,
    ty: PAD_Y - view.top * scale,
  };
}

/** Landmark fractions -> shared viewBox units. */
function toView(view, f) {
  const x = (xn) => +(f.tx + xn * view.width * f.scale).toFixed(2);
  const y = (t) => +(PAD_Y + t * BODY_H).toFixed(2);
  const runs = (m) => (m && m.runs ? m.runs.map(([a, b]) => [x(a), x(b)]) : []);
  const out = { landmarks: {}, profile: [] };
  for (const [k, m] of Object.entries(view.landmarks)) {
    out.landmarks[k] = { y: y(m.t), runs: runs(m) };
  }
  for (const p of view.profile) out.profile.push({ y: y(p.t), runs: p.runs.map(([a, b]) => [x(a), x(b)]) });
  if (view.crotchGap) out.crotchGap = { y: y(view.crotchGap.t), x: view.crotchGap.x.map(x) };
  out.midlineX = x(f.mid);
  return out;
}

const svgOf = (file) => fs.readFileSync(path.join('public/figures', file), 'utf8');

const views = [
  { key: 'front', src: 'front.svg', data: L.front },
  { key: 'back', src: 'back.svg', data: L.back },
];

const geometry = { viewBox: VIEW, padY: PAD_Y, bodyHeight: BODY_H, views: {} };

for (const v of views) {
  const f = fit(v.data);
  // Carry the <path> element across verbatim. Rebuilding it dropped potrace's
  // fill-rule="evenodd" and the figure flooded into a solid silhouette.
  const el = /<path[\s\S]*?\/>/.exec(svgOf(v.src));
  if (!el) throw new Error(`no path found in ${v.src}`);
  const out =
    `<svg xmlns="http://www.w3.org/2000/svg" width="${VIEW.width}" height="${VIEW.height}" ` +
    `viewBox="0 0 ${VIEW.width} ${VIEW.height}" version="1.1">\n` +
    `\t<g transform="translate(${f.tx.toFixed(3)} ${f.ty.toFixed(3)}) scale(${f.scale.toFixed(6)})">\n` +
    `\t\t${el[0]}\n` +
    `\t</g>\n</svg>\n`;
  fs.writeFileSync(path.join('public/figures', `figure-${v.key}.svg`), out);
  geometry.views[v.key] = toView(v.data, f);
  console.log(
    `figure-${v.key}.svg: source ${v.data.width}x${v.data.height} -> scale ${f.scale.toFixed(4)}, ` +
    `translate(${f.tx.toFixed(1)}, ${f.ty.toFixed(1)}), midline x=${geometry.views[v.key].midlineX}`
  );
}

fs.writeFileSync(
  'lib/figureGeometry.js',
  '// GENERATED by scripts/normalize-figures.js — do not edit by hand.\n' +
  '// Measured from the traced artwork in public/figures/, expressed in the\n' +
  '// shared viewBox both figures are drawn on. Zone boxes are fitted to these.\n' +
  `export const FIGURE_GEOMETRY = ${JSON.stringify(geometry, null, 2)};\n` +
  'export default FIGURE_GEOMETRY;\n'
);
console.log('\nWrote lib/figureGeometry.js');

const g = geometry.views;
console.log('\nAlignment check (shared viewBox units):');
for (const k of ['neck', 'shoulder', 'armpit', 'waist', 'handsEnd', 'crotch', 'ankle']) {
  const a = g.front.landmarks[k], b = g.back.landmarks[k];
  console.log(
    `  ${k.padEnd(10)} front y=${a ? a.y : '—'}   back y=${b ? b.y : '—'}` +
    (a && b ? `   Δ ${Math.abs(a.y - b.y).toFixed(1)}px` : '')
  );
}
